### ISSUE TITLE
Street view from Android app - no longer working

### ISSUE THREAD

**Issue by davoutuk** [zyzdev/flutter_street_view#17]
A day or so ago I started to get the following errors whenever I try to show 'street view' content in my Android app. All I get is a blank dark display with no street view displayed.

```
W/DynamiteModule(22111): Local module descriptor class for com.google.android.gms.googlecertificates not found.
I/DynamiteModule(22111): Considering local module com.google.android.gms.googlecertificates:0 and remote module com.google.android.gms.googlecertificates:7
I/DynamiteModule(22111): Selected remote version of com.google.android.gms.googlecertificates, version >= 7
I/SnapshotHandler(22111): Unable to retrieve flag snapshot for com.google.android.libraries.consentverifier#com.eis.lejog.lejog, using defaults.
W/MobStoreFlagStore(22111): Unable to update local snapshot for com.google.android.libraries.consentverifier#com.eis.lejog.lejog, may result in stale flags.
W/MobStoreFlagStore(22111): java.util.concurrent.ExecutionException: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.eis.lejog.lejog, sha256=[], atk=false, ver=222658040.true (go/gsrlt)
W/MobStoreFlagStore(22111): 	at ahv.s(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):3)
W/MobStoreFlagStore(22111): 	at ahv.get(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at ajf.g(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at xx.d(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):1)
W/MobStoreFlagStore(22111): 	at xz.run(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):0)
W/MobStoreFlagStore(22111): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/MobStoreFlagStore(22111): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/MobStoreFlagStore(22111): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/MobStoreFlagStore(22111): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/MobStoreFlagStore(22111): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
W/MobStoreFlagStore(22111): 	at java.lang.Thread.run(Thread.java:923)
W/MobStoreFlagStore(22111): Caused by: java.lang.SecurityException: GoogleCertificatesRslt: not allowed: pkg=com.eis.lejog.lejog, sha256=[], atk=false, ver=222658040.true (go/gsrlt)
W/MobStoreFlagStore(22111): 	at android.os.Parcel.createExceptionOrNull(Parcel.java:2373)
W/MobStoreFlagStore(22111): 	at android.os.Parcel.createException(Parcel.java:2357)
W/MobStoreFlagStore(22111): 	at android.os.Parcel.readException(Parcel.java:2340)
W/MobStoreFlagStore(22111): 	at android.os.Parcel.readException(Parcel.java:2282)
W/MobStoreFlagStore(22111): 	at em.bc(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at rj.a(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):4)
W/MobStoreFlagStore(22111): 	at it.e(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at js.t(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at js.u(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):3)
W/MobStoreFlagStore(22111): 	at js.e(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):2)
W/MobStoreFlagStore(22111): 	at jw.handleMessage(:com.google.android.gms.dynamite_mapsdynamite@222658084@22.26.58 (150700-0):69)
W/MobStoreFlagStore(22111): 	at android.os.Handler.dispatchMessage(Handler.java:102)
W/MobStoreFlagStore(22111): 	at android.os.Looper.loop(Looper.java:223)
W/MobStoreFlagStore(22111): 	at android.os.HandlerThread.run(HandlerThread.java:67)

```

**Comment by irjayjay** [comment]
Same issue here. I thought it was my API restrictions on the key I got from google, but turns out even if I turn off all restrictions it simply doesn't work.

**Comment by irjayjay** [comment]
I think my issue is that our project is still stuck on Flutter 2 and I can't use the latest version of this library because of it.
