### ISSUE TITLE
If there is no street view at a latitude and longitude, my application will crash.

### ISSUE THREAD

**Issue by abicai** [zyzdev/flutter_street_view#35]
`FlutterGoogleStreetView(
                  initPos:LatLng(13.5895478, 108.4401173),
                  // initSource: street_view.StreetViewSource.outdoor,
                )
`
13.5895478, 108.4401173 There is no street view at this longitude and latitude, and it will crash when running.
Is there any way to avoid. 
Besides requesting the api to verify if street view is available?

**Comment by abicai** [comment]
Even if there is a street view at this location, it will crash.(22.34697, 114.16579)
This error will be prompted!
`E/AndroidRuntime( 5535): com.google.maps.api.android.lib6.common.apiexception.f: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter location
E/AndroidRuntime( 5535): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.dynamite_mapsdynamite@222615099@22.26.15 (190408-0):23)
E/AndroidRuntime( 5535): 	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.dynamite_mapsdynamite@222615099@22.26.15 (190408-0):0)
E/AndroidRuntime( 5535): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime( 5535): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime( 5535): 	at android.os.Looper.loopOnce(Looper.java:210)
E/AndroidRuntime( 5535): 	at android.os.Looper.loop(Looper.java:299)
E/AndroidRuntime( 5535): 	at android.app.ActivityThread.main(ActivityThread.java:8123)
E/AndroidRuntime( 5535): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5535): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
E/AndroidRuntime( 5535): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
E/AndroidRuntime( 5535): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter location
E/AndroidRuntime( 5535): 	at zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange(Unknown Source:2)
E/AndroidRuntime( 5535): 	at com.google.android.gms.maps.zzaj.zzb(com.google.android.gms:play-services-maps@@18.2.0:1)
E/AndroidRuntime( 5535): 	at com.google.android.gms.maps.internal.zzbm.zza(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime( 5535): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime( 5535): 	at android.os.Binder.transact(Binder.java:1169)
E/AndroidRuntime( 5535): 	at em.bc(:com.google.android.gms.dynamite_mapsdynamite@222615099@22.26.15 (190408-0):2)
E/AndroidRuntime( 5535): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.dynamite_mapsdynamite@222615099@22.26.15 (190408-0):22)
E/AndroidRuntime( 5535): 	... 9 more
W/mple.test_theme( 5535): type=1400 audit(0.0:24261780): avc: denied { search } for name="mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
W/mple.test_theme( 5535): type=1400 audit(0.0:24261781): avc: denied { search } for name="mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
W/mple.test_theme( 5535): type=1400 audit(0.0:24261782): avc: denied { search } for name="mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
W/mple.test_theme( 5535): type=1400 audit(0.0:24261783): avc: denied { search } for name="mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
W/mple.test_theme( 5535): type=1400 audit(0.0:24261784): avc: denied { getattr } for path="/data/mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
W/mple.test_theme( 5535): type=1400 audit(0.0:24261785): avc: denied { search } for name="mqsas" dev="dm-53" ino=401 scontext=u:r:untrusted_app:s0:c107,c257,c512,c768 tcontext=u:object_r:mqsas_data_file:s0 tclass=dir permissive=0 app=com.example.test_theme
I/Process ( 5535): Sending signal. PID: 5535 SIG: 9
`

**Comment by sadiqkhan61651** [comment]
Same issue

**Comment by justintoth** [comment]
Same issue.

**Comment by liorboyango** [comment]
See solution here: https://github.com/zyzdev/flutter_street_view/issues/39

**Comment by yogi1610** [comment]
@justintoth 
@sadiqkhan61651 
@abicai 
Does somebody found the solution of app keep crashing?
