### ISSUE TITLE
App Keeps crashing 

### ISSUE THREAD

**Issue by yogi1610** [zyzdev/flutter_street_view#42]
Using flutter_google_street_view: ^3.1.4 package which causing app to be crashed continuosly.
bug is

E/AndroidRuntime(29446): com.google.maps.api.android.lib6.common.apiexception.f: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:318)
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.e.run(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:3)
E/AndroidRuntime(29446): 	at android.os.Handler.handleCallback(Handler.java:942)
E/AndroidRuntime(29446): 	at android.os.Handler.dispatchMessage(Handler.java:99)
E/AndroidRuntime(29446): 	at android.os.Looper.loopOnce(Looper.java:201)
E/AndroidRuntime(29446): 	at android.os.Looper.loop(Looper.java:288)
E/AndroidRuntime(29446): 	at android.app.ActivityThread.main(ActivityThread.java:7872)
E/AndroidRuntime(29446): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(29446): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
E/AndroidRuntime(29446): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
E/AndroidRuntime(29446): Caused by: java.lang.NullPointerException: Parameter specified as non-null is null: method zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange, parameter location
E/AndroidRuntime(29446): 	at zyz.flutter.plugin.flutter_google_street_view.FlutterGoogleStreetView.onStreetViewPanoramaChange(Unknown Source:2)
E/AndroidRuntime(29446): 	at com.google.android.gms.maps.zzaj.zzb(com.google.android.gms:play-services-maps@@18.2.0:1)
E/AndroidRuntime(29446): 	at com.google.android.gms.maps.internal.zzbm.zza(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime(29446): 	at com.google.android.gms.internal.maps.zzb.onTransact(com.google.android.gms:play-services-maps@@18.2.0:3)
E/AndroidRuntime(29446): 	at android.os.Binder.transact(Binder.java:1164)
E/AndroidRuntime(29446): 	at m.axi.c(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323.661367323:8)
E/AndroidRuntime(29446): 	at com.google.maps.api.android.lib6.streetview.camera.i.g(:com.google.android.gms.policy_maps_core_dynamite@243125309@243125304049.661367323

MUST FIX THIS BUG AND PROVIDE THE NEW UPDATED VERSION

**Comment by subins829** [comment]
Any update on this issue ?
